name: mcp-server-chart
services:
  sse:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/sse/Dockerfile
    ports:
      - "1123:1123"

  streamable:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/streamable/Dockerfile
    ports:
      - "1122:1122"
